apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: showup2move
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: showup2move.local
