apiVersion: v1
kind: ConfigMap
metadata:
  name: showup2move-config
data:
  NODE_ENV: production
  NEXT_PUBLIC_APP_URL: https://showup2move.example.com
  S3_BUCKET_NAME: showup2move-media
  S3_REGION: local
