apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: showup2move
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  ingressClassName: nginx
  rules:
    - host: showup2move.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: showup2move-web
                port:
                  name: http
