apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-ingress
spec:
  podSelector:
    matchLabels:
      app: showup2move-web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 3000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-data-from-apps
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - postgres
          - redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - showup2move-web
                  - showup2move-worker
                  - showup2move-toolbox
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-toolbox-internal
spec:
  podSelector:
    matchLabels:
      app: showup2move-toolbox
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5000
